### ISSUE TITLE
Increase image size limit 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1026]
* Bump size limit to 10MB

**Comment by mirunacurtean** [comment]
@akatsoulas 
This is definitely taking more than I estimated, due to actually trying to get perfectly sized images for boundry testing but I have an update: 
1. PNG images of under 1 MB and above it at 1.5 MB have been upload sucessfully on both media gallery and questions reply. 
2. GiF images can be uploaded but they are [transformed/present as PNG](https://github.com/mozilla/sumo/issues/468). 
3. JPEG images could not be uploaded due to the second modal closing after a file upload while adding the title and description info. This is a consistent isssue. 
![jpeg upload can be closed in progress](https://user-images.githubusercontent.com/53306802/173621865-2b02904c-95ee-49d4-a5cc-9dc6a7722be4.gif)

![image](https://user-images.githubusercontent.com/53306802/173622035-9cc61685-65fd-4cb0-8980-a03b7574157e.png)

**Comment by mirunacurtean** [comment]
Additional feedback on images:

- I managed to also reproduced the comments from the community posts in regrads to the uploading error. See https://github.com/mozilla/sumo/issues/1049

- Trying to upload a [larger sample PNG (appx 4 MB) ](https://photos.app.goo.gl/pcMFMsQZSopqAUyi6) results in it being resized and losing functionality
- PNG larger than 10 MB won't be qualified to continue to upload process. Might be useful to have an info text like the one concerning the accepted formats. 
![image](https://user-images.githubusercontent.com/53306802/173829516-c5645f7a-493b-4283-be7f-b079c0f9a2ec.png)

**Comment by mirunacurtean** [comment]
Marking this as Ready for Release as the tickets for Gif and Jpeg respectively have been added/ updated.

**Comment by kelimuttu** [comment]
@mirunacurtean is there any estimation on when we're going to release this?

**Comment by mirunacurtean** [comment]
@kelimuttu I don't think this is going to fix all the upload issues, as they still happen with a larger sized file (around 1 MB for JPEG).
This is an improvment on the file size that can be uploaded, and that I had considered confirmed through the fact that the PNG images up to 10MB are accepted through the Preview modal and then uploaded while PNG files above 10 MB are not. 
For the uploads fails I've created and linked all the related issues above so that it can be seen there are separate.

**Comment by kelimuttu** [comment]
Aah, thanks for clarifying @mirunacurtean 

From what you mention above, does it mean that we will have different size limit for different image type?

**Comment by akatsoulas** [comment]
Closing this for PNGs. The other two issues have been prioritized

**Comment by mirunacurtean** [comment]
> Aah, thanks for clarifying @mirunacurtean
> 
> From what you mention above, does it mean that we will have different size limit for different image type
@kelimuttu 
In order to have images rendred the way they are intended I recommend keeping the images (JPEG and PNG, the ones which seem to be working) under 1 MB. This applies to both types to it's not a different size limit, it's just that the upload fails will have manifested differently from what I have seen when you go above that size.

**Comment by kelimuttu** [comment]
Gotcha. Thanks, @mirunacurtean 

In the future, maybe we can consider adding a note about the upload size limit on the upload modal.
