### ISSUE TITLE
[jQuery] Unable to insert media from media gallery in posts

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1085]
**Describe the bug**
The insert media modal does not load any images in order to use them in posts. 

**To Reproduce**
1. Go to https://support.allizom.org/en-US/forums/contributors/712963#thread-reply
2. Click on Insert MEdia button. 
3. Inspect the modal.
4. Type in a file title and search for it.

**Expected behavior**
Images are preloaded in the modal in order to be selected, 
A search can further filter them. 
![image](https://user-images.githubusercontent.com/53306802/185145264-58b89115-1003-47f9-aa8f-fc671c8645f0.png)

**Screenshots**
Current issue.

![image](https://user-images.githubusercontent.com/53306802/185145350-1f49c9f3-2ceb-46b7-b748-6e50987ae696.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox, Chrome
 - Version stable

**Additional context**

**Comment by akatsoulas** [comment]
@smithellis could you maybe take a look at this?

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/5214

**Comment by mirunacurtean** [comment]
@smithellis @akatsoulas  Yay, images are showing but we have a different problem https://github.com/mozilla/sumo/issues/109. 
I logged it in a separate ticket but it will need to be fixed in order for me to test the full functionality here as well.

**Comment by mirunacurtean** [comment]
Thank you for the fix on #1099. Now that that is done I am able to check further. 
The ability to see images (english and non-english) works and this also aplies to english locale videos (see [1061](https://github.com/mozilla/sumo/issues/1061) for non-english videos). 

There seems to be a problem with actually [displaying some of the images](https://support.allizom.org/en-US/forums/contributors/712952?last=73642#post-73642) and I'm currently looking to see if we have something like this logged or if it's just another stage specific data issue. 
![image](https://user-images.githubusercontent.com/53306802/189840536-4b1640a4-dbfd-4588-a546-15d8f13d4deb.png)

**Comment by escattone** [comment]
(cc @smithellis @akatsoulas) Thanks @mirunacurtean, the problem you identified above,

> that trying to [insert an image from a non-English locale](https://support.allizom.org/en-US/forums/watch-and-notify/712965?last=73652#post-73652) results in "The image [image name] does not exist" message.

is not a new problem. It exists on production, and is not related to the `jQuery` upgrade.

The problem is that we allow the user to select an image from any locale, but we don't include the selected image's locale in the Wiki image tag, only its title. So we lose that information, the locale of the image. When we preview or post the reply containing that image tag, the Wiki parser finds the image tag, extracts the title, and then searches for an image with that title _**in the locale of the forum, not the locale of the image**_. It's only by chance that sometimes an image with the same title exists in the locale of the forum.

This should not hold up the release tomorrow, since this is not a new bug. It's a bug that seems to have existed for a long time.

@mirunacurtean Since you found this bug, would mind creating a new issue for it?

**Comment by mirunacurtean** [comment]
@escattone Thank you for the investigation into this later issue. I added https://github.com/mozilla/sumo/issues/1101 for the "Image does not exist" issue. 
Otherwise, this is then confirmed as working with no other regressions introduced by jquery and it is ready for release.
