### ISSUE TITLE
 https://support.mozilla.org should send strings through webchannels

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1095]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1786650

**Comment by escattone** [comment]
@mirunacurtean The QA for this should be simple:

**Comment by mirunacurtean** [comment]
@escattone In tried and then I remembered that on stage the is a [certain setup](https://github.com/mozilla/sumo/issues/507#issuecomment-663432823) that must be made in order to get the Share data working. I tried but I think I'm having the same problem as the first time, setting the permissions file correctly.
