### ISSUE TITLE
Unable to connect error when trying to switch to a different locale 

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#1098]
**Describe the bug**

**To Reproduce**
1. Login and select the Es locale. 
2. Go to https://support.mozilla.org/en-US/gallery/images
3. From the Show media for dropdown select the English language 
4. Notice the error. 

**Expected behavior**
If there are no videos or images in this language then the appropriate message should be posted. 
![image](https://user-images.githubusercontent.com/53306802/188171992-d5b89e1a-9ef2-4588-8c1d-3ca185685a16.png)

**Screenshots**
![media gallery switch from es to english](https://user-images.githubusercontent.com/53306802/188172160-25945552-6822-4790-a232-7bbbc98d4eab.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version latest

**Additional context**
Occurs when sumo locale is set to english and the switch to another language is made. Occurs fro both images and videos and in production as well.

**Comment by emilghittasv** [comment]
This issue is verified fixed on stage. 

Switching the language via the "Show media for" dropdown menu or via the footer section while on the Media Gallery page will successfully redirect to the appropriate page locale.

Tested on desktop using: Firefox, Chrome & Safari browsers 
Tested on mobile (both iOS & Android) on: Safari (on iOS) & Firefox (on Android) browsers 

Marking this ticket as ready for release.
