### ISSUE TITLE
Clicking What's New in the Hebrew localized version of Fenix goes to a 404 page

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1106]
More info
https://github.com/mozilla-mobile/fenix/issues/24688

**Comment by escattone** [comment]
See https://stackoverflow.com/questions/8202406/locale-code-for-hebrew-reference-to-other-locale-codes

This seems to be due to the way the Java version 16 `Locale` class works (see https://developer.android.com/reference/java/util/Locale.html#legacy-language-codes), mapping `he` to `iw` for backwards compatibility. So instead of using https://support.mozilla.org/1/mobile/*/*/he/whats-new-firefox-android, Fenix uses https://support.mozilla.org/1/mobile/*/*/iw-IL/whats-new-firefox-android.

**Comment by escattone** [comment]
This was completed when https://github.com/mozilla/kitsune/pull/5241 was released.
