### ISSUE TITLE
Signup contributors to new contributor groups

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1108]
New contributors when signing up, they will be registered to different groups depending the area of contribution they picked to registered from

**Comment by mirunacurtean** [comment]
Signup from Contributor area results in creating an account in production. 
![image](https://user-images.githubusercontent.com/53306802/196136276-69307bbc-5768-4983-b09a-f173a667e308.png)

@akatsoulas Do you have any idea if we have ny preference that makes FxA point towrds stage so that we can verify that depending on the signup point the user is asigned an prefered contribution area?

**Comment by mirunacurtean** [comment]
Confimed for each contribution area.
@akatsoulas Should a new contribution area be added when a users signs in through the Contribute/ Sign up path again? 
![mobile contributor signs up as localization  contributor](https://user-images.githubusercontent.com/53306802/198591907-bd4ecd7e-831f-460c-9021-c6631a6a6dea.gif)

**Comment by akatsoulas** [comment]
I am not sure. I would say no and we can revisit this if needed.

**Comment by mirunacurtean** [comment]
Ok. Added https://github.com/mozilla/sumo/issues/1134 to revisit if needed.
