### ISSUE TITLE
Search results pages should not be crawlable 

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1127]
These pages should not be crawlable, as they will not be indexed (they are not good internet search results and Google will not use them). It is best to obscure the links that produce search results, in addition to the noindex tag that is currently in place.

**Comment by mirunacurtean** [comment]
@escattone Hello, I did not move this ticket since I was under the impression that it's not testable. Is that correct, or could we think of a way to setup a test case for this situation?

**Comment by escattone** [comment]
@mirunacurtean I'm sorry, I should have put some QA notes on this ticket! So here they are:
- There's really no way to test the changes to https://support.allizom.org/robots.txt, because they'll only be used on production not stage.
- Open https://support.allizom.org/en-US/search/?q=firefox in the browser with devtools, and check that the HTML returned contains `<meta name="robots" content="noindex, nofollow">`


<img width="920" alt="image" src="https://user-images.githubusercontent.com/3743693/211874312-0d92a80e-c89f-4960-9c11-99efe13e844c.png">

**Comment by mirunacurtean** [comment]
I can confirm, thanks for the tip.
![image](https://user-images.githubusercontent.com/53306802/213647530-e3696370-35c6-4c26-9041-7af044067f04.png)
