### ISSUE TITLE
FXAAuthBackend instance has no request attribute in Celery task process_event_profile_change

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1177]
https://sentry.io/share/issue/87379d7338e64e1f98c3e1157822e4e5/

When processing FxA profile change events with the `process_event_profile_change()` Celery task, we create an instance of the `FXAAuthBackend` class, and then call that instance's `update_user()` method. The `update_user()` method depends on the instance having a valid `request` attribute, which it never does because it has never been through the authentication process.

This error has occurred 728 times in the last 16 days, and seems to be blocking every attempt to update a SUMO user from an FxA profile-change event.

**Comment by escattone** [comment]
# QA Notes
@mirunacurtean In terms of QA, there is really nothing that you can do for this one.

**Comment by mirunacurtean** [comment]
@escattone I've followed all those steps. 
After, I have done the following:
1. Left the Firefox Accounts page open and returned to the sumo profile page and reloaded it. I was expecting it not to show an updated email adress, though. 
2. Signed out and signed in with the account I had just made primary, and since it was an account that had not not been signed up on sumo before, I got the Welcome banner. 
3. 
![image](https://user-images.githubusercontent.com/53306802/214477433-739893d4-d414-44c7-8662-db202d1ab473.png)
4. Went the profile (the primary email is listed) and then acessed the Firefox account where I verified that the primary and secondary emails were the ones that had just been inversed. 
5. I was also able to log in with the secondary email. Went to the profile (the secondary email is listed) and the to the Firefox account. Data is identical to step 4, in that area. 

Are these the expected results?
