### ISSUE TITLE
Allow only specific HTML attributes in messages

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1210]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1819800

**Comment by emilghittasv** [comment]
I can confirm that the issue mentioned in https://bugzilla.mozilla.org/show_bug.cgi?id=1819800 is verified fixed on stage, in our messaging system, by the changes performed in https://github.com/mozilla/kitsune/compare/b60adcc458d7...1f7b203c98b0. Class attributes are no longer allowed.

During the verification of this ticket, I noticed that this issue can be still reproducible in other parts (like AAQ questions or forum threads). Filled under https://github.com/mozilla/sumo/issues/1211

I've also tested a couple of the allowed attributes for the tags specified inside the ALLOWED_MESSAGE_ATTRIBUTES list and can confirm that the allowed ones are applied successfully while other attributes (which are not part of that list) are not applied. During this verification, I noticed that the anchor tag is not successfully constructed (filled under https://github.com/mozilla/sumo/issues/1212) but this is not a regression caused by this change (also reproducible in production).

Marking this ticket as ready for release.
