### ISSUE TITLE
create endpoint for getting information about the current user

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1266]
One of the requirements of Firefox device-migration UI wizard is that if the current user is signed into SUMO, the FxA browser sign-in form will be pre-populated with that user's email address. I think the best approach is to provide a SUMO endpoint that can be queried by the JS which will return information about the current user.

**Comment by emilghittasv** [comment]
Since this query is not currently implemented/used at UI level (in the current state of our stage environment) I've queried our /graphql endpoint using the following query string: `query {
        currentUser {
          email
        }
      }`

Queried while logged in returns `currentUser	Object { email: "eghitta@mozilla.com" }`

![image](https://github.com/mozilla/sumo/assets/28087895/a0c91e3b-5220-475d-bf29-0bd2f8b2c5c4)

Queried while logged out returns `Object { currentUser: null }`

![image](https://github.com/mozilla/sumo/assets/28087895/fbe54d7a-b828-4032-ad14-4c13c139e315)


I believe that we can mark this as ready for release

**Comment by emilghittasv** [comment]
Also, confirmed at UI level (after enabling UI tour for stage environment) that the Email field fetches the email information from our endpoint

![image](https://github.com/mozilla/sumo/assets/28087895/b3c06d6f-c105-4d41-860d-10b7fe881cf1)
