### ISSUE TITLE
[Postgres][Dev] Username search results are retrieved slower in dev compared with the other envs

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1449]
**Preconditions**
Sign in to SUMO

**Steps to reproduce**
1. Go to https://support-dev.allizom.org/en-US/messages/new
2. Type a username inside the "To" field (example: pwt)

**Expected behavior**
The search results are displayed at a similar speed compared with `stage` and `prod`

**Actual behavior**
Search results are displayed slower compared to `stage` and `prod`

**Screencasts**
![search](https://github.com/mozilla/sumo/assets/28087895/d51d25a8-a8b1-4abd-aaa2-a3d6054cffa0)

**Desktop:**
 - OS: Chrome
 - Browser: Firefox.

**Additional Notes:**
- Searching for the same string again brings up the search results quite instant.
- This issue is reproducible in dev environment. Prod and Stage are not affected.

**Comment by escattone** [comment]
After some research within the `dev` and `prod` environments, the root cause seems to be the fact that we're using a case-sensitive collation in Postgres but the search on the `Profile` and `User` classes is performed case-insensitive (`name__istartswith` and `username__istartswith`). The case-insensitive searches on the `Profile` and `User` tables run at least 3 times faster in MySQL.

Another problem is that we're doing `Profile.objects.filter(Q(name__istartswith=pre))` but the `Profile` table has no database index on the `name` column, but both MySQL and Postgres suffer from that omission.

**Comment by escattone** [comment]
@emilghittasv I've included an [improvement](https://github.com/mozilla/kitsune/commit/682b37c8204c6f31879e4e05e8438c039f3d3bd0) for this issue in the `switch-to-postgres` branch and pushed that branch to the `dev` environment. From my own testing, it improved the username search from ~15 seconds to ~6-8 seconds. I think that's all we'll be able to do for this one. The search using MySQL takes only ~3-4 seconds, and will always be faster because of the case-insensitive collation used.

The only other option that we could consider would be to make the search case sensitive in Postgres, so `pwt` and `Pwt` would be different searches, but that's a change in functionality/ease-of-use.

**Comment by emilghittasv** [comment]
@escattone 

I can confirm that the search results for usernames are retrieved faster now (stil not as fast as MySQL). But I agree that we should probably refrain on making search case sensitive in Postgres. I think that, from a user perspective is better to provide both uppercase and lowercase results for the search term regardless of the case being used.

I'm going to close this ticket. Thank you!
