### ISSUE TITLE
Firefox Accounts Main Navigation

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1471]
Change main navigation to reflect new nav items for Mozilla Accounts.  Change Firefox Accounts to Mozilla Accounts.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5644

**Comment by emilghittasv** [comment]
QA work is finalized for this ticket.

Verified that:
* The top-navbar "Get Help" subpanel has been successfully updated and now contains a third column (the "Mozilla Account" entry)
* Verified that clicking on the "Reset Password" option redirects the user to the https://accounts.firefox.com/reset_password page.
* Verified that clicking on the "Sync My Data" option redirects the user to the Switching Devices kb article page.
* Verified that clicking on the "Get Help" option redirects the user to the mozilla-account product page.
* Verified that the "Get Help" top-navbar subpanel is accessible/successfully displayed on mobile devices (Huawei P40 pro and iPhone 11). Also the menu items are clickable.
* Verified that the "Get Help" top-navbar subpanel is responsive to browser window width shrinks.
* Verified that the "Mozilla Account" section is displayed for both signed in & signed out users.

During the verification of this ticket I've noticed and filled the following:
* The order of the elements inside the "Mozilla Account" subpanel are not as per the design specified inside the Figma doc. Filled under -> https://github.com/mozilla/sumo/issues/1510
* Clicking on the "Mozilla Account" header redirects the user to the products page instead of the Mozilla Account page. Also, on the same note, clicking on the "What is it?" link redirects the user to https://www.mozilla.org/en-US/firefox/accounts/ instead of https://support.mozilla.org/en-US/kb/access-mozilla-services-firefox-account .Both filled under https://github.com/mozilla/sumo/issues/1513

The newly logged issues don't have the necessary impact of blocking this ticket from being moved inside the "Release" column.
