### ISSUE TITLE
Firefox Accounts Footer Navigation

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1472]
Footer navigation updated for Mozilla Accounts.

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5645

**Comment by emilghittasv** [comment]
I can confirm, on a locally built build that the "Firefox Accounts" footer option was renamed to "Mozilla Accounts" and it also contains the following options:

* Sign In/Up
* What is it? 
* Reset Password
* Sync My Data
* Get Help

Since this change lives inside the mozilla-accounts branch for now, I'm closing this ticket instead of moving it inside the "Release" column.
