### ISSUE TITLE
Rework interstitial for MA Login

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1493]

**Comment by akatsoulas** [comment]
PR against main branch https://github.com/mozilla/kitsune/pull/5677

**Comment by emilghittasv** [comment]
QA work is done for this ticket.

Testing activities performed:
* Exploratory testing in order to verify that different entry points to the `/auth` page are redirecting to the new login interstitial now.
* Verified that users can successfully sign in or create a new account by clicking the "Sign in or Sign up" button from the login interstitial.
* Verified that the login interstitial contains the expected strings & format.
* Verified that the new login interstitial card is compatible to browser window shrink, screen readers & high contrast themes.
* Verified that the new login interstitial card is successfully displayed on mobile devices (Huawei P40 Pro and iPhone 11) and functional.
* Verified that the "Terms and Conditions" and "Privacy Policy" links are successfully redirecting the user to the desired pages.

During the verification of this ticket I've noticed & filled a small UI issue -> https://github.com/mozilla/sumo/issues/1512

Verification was performed using: Chrome, Firefox & Safari browsers.

Moving this ticket inside the "Release" column.
