### ISSUE TITLE
change from "Firefox account(s)" to "Mozilla account(s)"

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1507]
Replace the following in our codebase:
- `Firefox account` --> `Mozilla account`
- `Firefox accounts` --> `Mozilla accounts`
- `create` --> `sign up`
- `login`(verb) --> `sign in`
- `login`(noun) remains the same
- use `Manage account` instead of `Edit account` or `View account`

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed on `stage`. 

Verifications performed:
* Verified that the popular searches option is `Mozilla accounts` instead of `Firefox Accounts`
* Verified that the footer option changed from `Mozilla Accounts` to `Mozilla accounts`
* Verified that the `Manage Firefox Account` button from the edit profile section was renamed to `Manage account`
* Verified that the hidden option from the my profile section (`Delete My Account`) was successfully renamed to `Delete Your Account`
* Verified that the switching-devices wizard contains the expected changes.
* Performed a bit of exploratory session to catch any potential missed placed.

During the verification of this ticket I've noticed that the newly added top-navbar option (Mozilla Account) contains `Mozilla Account` instead of `Mozilla account` inside the description section. Filled under https://github.com/mozilla/sumo/issues/1519

Moving this ticked inside the "Release" column.
