### ISSUE TITLE
Zendesk ticket subjects fallback should be to friendly name vs. value

### ISSUE THREAD

**Issue by smithellis** [mozilla/sumo#1556]

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5776

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5798

**Comment by emilghittasv** [comment]
This is verified in `stage`.

* The `No response provided.` message is added inside the Zendesk ticket description field if the `Tell us more` contact field was left empty.
* The data added inside the `Tell us more` is successfully added inside the Zendesk ticket description field (instead of `No response provided.`)
* The product + support (example: `Mozilla Account support`, `MDN Plus support`) is successfully added inside the Zendesk ticket subject field if the `Subject` form field was left empty.
* The data added inside the `Subject` form field is successfully added inside the Zendesk ticket subject field (instead of the product + support)

During my testing activities I've covered all of our premium products (I've sent Zendesk tickets for all premium products and can confirm that the above bulletpoints are respected) while logged in to SUMO & also tested the above on the loginless form. 

I'm moving this ticket inside the `release` column.
