### ISSUE TITLE
Do not update profile details in ZD from loginless flows

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1566]
When a ticket is submitted through the loginless flow in ZD we need to create a profile only when there's not one. If there is a profile we should not update any values. We should research into options to flag that ticket also as loginless

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5768
https://github.com/mozilla/kitsune/pull/5769

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`.

* Sending a loginless form with an e-mail address which is not linked to an existing SUMO account will create the Zendesk ticket as an Anonymous user.
* Creating a SUMO user using the e-mail account above (which was used to send a loginless ticket) and sending another Zendesk ticket will update the Zendesk username from Anonymous user to the actual username.
* Sending a loginless form with an e-mail address which is linked to an existing SUMO account will not update the Zendesk username to "Anonymous user"

I'm moving this ticket inside the `release` column.
