### ISSUE TITLE
Add a priority queue in Celery

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1573]
We should add another queue in celery which will be used for non resource intensive tasks like sending an email

**Comment by smithellis** [comment]
https://github.com/mozilla/kitsune/pull/5804
or
https://github.com/mozilla/kitsune/compare/main...smithellis:kitsune:celery-alternate-queue

Need some feedback on this.

**Comment by akatsoulas** [comment]
https://github.com/mozilla/kitsune/pull/5815

**Comment by escattone** [comment]
# QA Results
These are the QA results related to https://github.com/mozilla/kitsune/pull/5815 as tested on stage:
- [Typo in one of the Celery task routes](https://github.com/mozilla/kitsune/blob/e7301f33f5adcf40f12619ec0aee689d890332e7/kitsune/celery.py#L12).
- The task route [`kitsune.messages.tasks.email_private_messages`](https://github.com/mozilla/kitsune/blob/e7301f33f5adcf40f12619ec0aee689d890332e7/kitsune/celery.py#L15) does not exist.
- Since the Celery workers run `bin/run-celery-worker.sh`, which doesn't specify an explicit list of queues to pull from, they pull from the default queue, which is just `celery`, so no tasks get pulled from the `priority` queue. I verified this by inspecting the active queues of each of the workers -- none of them knew of the `priority` queue -- and by checking the `priority` Redis queue, which had 80 tasks queued but never pulled. I think the easiest way to resolve this is to simply add `-Q celery,priority` to the `celery` command in [`bin/run-celery-worker.sh`](https://github.com/mozilla/kitsune/blob/e7301f33f5adcf40f12619ec0aee689d890332e7/bin/run-celery-worker.sh#L3).

**Comment by escattone** [comment]
# QA Results
These are the QA results related to https://github.com/mozilla/kitsune/pull/5822 as tested on stage:
- ✅ Verified that all of the Celery workers are pulling from both the `celery` and `priority` queues (`kubectl exec` into one of the pods, and run `celery -A kitsune inspect active_queues`).
- ✅ Verified that a `kitsune.tidings.tasks.send_emails` task was generated and consumed via the `priority` queue.

Moving this to the `release` status.
