### ISSUE TITLE
Email Bandit does not provide information regarding the original intended recipient 

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1581]
**Describe the bug**
For both `dev` and `stage` we have Email Bandit in place in order to test e-mail notifications. Unfortunately, Email Bandit does not provide information regarding the original recipient of the e-mail (only the e-mail that it's being used to redirect that traffic to). This makes it hard for the verification of some test scenarios (example: Watching a particular question,thread, kb article, etc with a certain user and verifying that e-mail notifications are sent to that particular user when an update was performed).

**Comment by escattone** [comment]
I looked at the `django-email-bandit` source code, and the original email recipients should be in the body of the bandit email at the very beginning, prior to the real content. Here's what the bandit template has:
```
================================================================================

This email was hijacked by django-email-bandit!
Below are the original recipients:
{% spaceless %}{% for email in previous_recipients %}{{ email }}
{% endfor %}{% endspaceless %}

================================================================================
```

My guess is that this information is present in all of the bandit emails, but since it's not HTML, we'll have to use Gmail's `Show original` option in order to see the original recipients via the raw source.

**Comment by emilghittasv** [comment]
Indeed! Thank you so much @escattone! 

The original recipients are listed inside the raw source (when using `show original` option)

![image](https://github.com/mozilla/sumo/assets/28087895/722e4835-9893-4bfd-85e3-b8608594b55d)

Thank you so much for investigating this and pointing out the solution!

I believe that we can go ahead and close this ticket.
