### ISSUE TITLE
"An Error occured" when trying to leave a reply to an AAQ question (Sentry fires: TimeoutError)  

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1676]
**Preconditions**
Sign in to SUMO with an account that doesn't have any special permissions & doesn't belong to any group. 

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/questions/new/desktop/form (or any other AAQ form)
2. Post a question.
3. Leave a reply to that question.

**Expected behavior**
The reply is successfully submitted.

**Actual behavior**
The "Oh, no! It looks like an unexpected error occurred. We've already notified the site administrators. Please try again now, or in a few minutes" is displayed and the https://mozilla.sentry.io/issues/4997181498/?project=4504326797197312&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=0 sentry error is fired.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by escattone** [comment]
This was caused by the combination of the following two factors:
- The `timeout` function of the `timeout-decorator` package does not support Python 3.11.8 or greater (and is not actively maintained).
- When we released on Feb. 15, we pulled in the newly released 3.11.8 version of the `python:3.11-bookworm` Docker image.
