### ISSUE TITLE
[GA4] The "search-result.kb-article", "search-result.support-forum-question-detail" and "search-fallback.kb-article" events are not being sent to GA

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1704]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/
2. Inside the search input field type a valid article name (example: "insecure password warning")
3. Click on one of the listed articles.
4. Inside the search input field type an invalid article name which returns no results.
5. Click on one of the articles listed inside the recommended/fallback list.
6. Navigate to the https://support.allizom.org/en-US/questions/all#search page.
7. Inside the search bar type a valid question title.
8. Click on one of the returned search results.

**Expected behavior**
Step 3: The `click_internal_link` event with `search-result.kb-article` param is sent to GA.
Step 5: The `click_internal_link` event with the `search-result.support-forum-question-detail` param is sent to GA.
Step 8: The `click_internal_link` event with the `search-fallback.kb-article` param is sent to GA.

**Actual behavior**
No GA events are sent for step 3, 5 & 8

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by escattone** [comment]
This issue occurs only when clicking on search results from "instant" searches (all searches made on pages other than the [search home page](https://support.allizom.org/en-US/search/)), and is due to the fact that the dynamically-added "instant" search results hadn't been instrumented with event listeners. I've added a [fix](https://github.com/mozilla/kitsune/pull/5914/commits/dbaa7019d745e1f8eeb9cdb2569f8bb5e6a9492a) for this in https://github.com/mozilla/kitsune/pull/5914.

**Comment by emilghittasv** [comment]
I can confirm that this issue is verified fixed in `stage`.

The  `click_internal_link event` with `search-result.kb-article`, `search-result.support-forum-question-detail`, `search-fallback.kb-article`  params is sent to GA successfully for "instant" search results.

Moving this ticket inside the `release` column.
