### ISSUE TITLE
[GA4] The dmw_state_report with configure-sync param is sent multiple times when refreshing the switching-devices kb article page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1718]
**Preconditions**
Ensure that you are signed in to FxA sync.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices and make sure that your are on the step 2 of the Wizard.
2. Refresh the page.

**Expected behavior**
Only one `dmw_state_report` event with `configure-sync` param is sent.

**Actual behavior**
The `dmw_state_report` event with the `configure-sync` param is sent 3 times.

**Screencasts**
![dmw_state_report_configure_sync](https://github.com/mozilla/sumo/assets/28087895/766614a4-1f8a-4f8a-9730-08d708b55037)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by escattone** [comment]
This issue won't cause any problems with our Google Analytics funnels that use this data, because the funnels are counting users with the reported state rather than the number of events. It's good to know about this, but I'm going to close this, since reporting the state multiple times on a state transition doesn't affect our interpretation of the data.
