### ISSUE TITLE
[GA4] The dmw_state_report with sign-into-fxa param is sent multiple times when refreshing the switching-devices kb article page

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1719]
**Preconditions**
Ensure that you are not connected to FxA sync.

**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/switching-devices and ensure that you are on the step 1 of the Wizard.
2. Refresh the page.

**Expected behavior**
The `dmw_state_report` event with the `sign-into-fxa` param is sent only once.

**Actual behavior**
The `dmw_state_report` event with the `sign-into-fxa` param is sent 3 times.

**Screencasts**
![dmw_state_report_sign-into_fxa](https://github.com/mozilla/sumo/assets/28087895/21d28f4d-f8bd-4586-9637-230d6d599e95)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Comment by escattone** [comment]
This issue won't cause any problems with our Google Analytics funnels that use this data, because the funnels are counting users with the reported state rather than the number of events. It's good to know about this, but I'm going to close this, since reporting the state multiple times on a state transition doesn't affect our interpretation of the data.
