### ISSUE TITLE
Introduce helpful information for KB articles

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1805]
We are going to display useful information about an article like when was last updated or if it's helpful below the title as displayed in the [design proposal](https://www.figma.com/design/5bdwOFssObTuqUxlJOa7We/Article-Experience-Redesign?node-id=221-2075&t=SIOujGIBjnjujA5o-0)

**Comment by emilghittasv** [comment]
QA activities are finalized for the first iteration of the KB metadata information work.

I can confirm the following:
- The product, last updated & helpfulness info is displayed on kb article pages (for both parent articles & translations)
- The product & last updated information is displayed for the kb article topics listing page. The helpfulness info is not displayed on these listing pages.
- The kb metadata info is displayed for all user types (non-contributor, contributor, staff & users which are not logged in to SUMO)
- The Product info successfully displays all products linked to the kb article in both the kb article page and inside the article topic listing page. When there are multiple products linked, the product acts as a tooltip which on hover will display the full list of products.
- Dynamically adding or removing a topic via the "Edit Article Metadata" section will successfully update the listed products inside the kb metadata info (for both the kb article, product topic listing page & for the translation version of the document).
- The `Last Update` info does update only when a new revision was submitted & approved and the time displayed represents the delta between the creation time of the last approved revision and now
- If a revision is approved for the parent article, the `Last Update` time for the translated article version is not updated. Same happens when approving a revision for the translated version, the `Last Update` time for the parent article is not updated.
- The kb article metadata info is not displayed for obsolete marked (archived) kb articles (for both the parent article and the translated versions). Removing the article from the obsolete state will display the article metadata info again successfully.
- The helpfulness percentage is successfully modified when down-voting or upvoting an article.
- If there are no votes, the helpfulness info is not displayed.
- Voting a parent article does not effect the helpfulness percentage displayed for the translated version of that article (and vice versa)

Some of the above verifications were performed for templates as well.

@escattone Please note that during the verification of this work, the following tickets were filled:
- https://github.com/mozilla/sumo/issues/1813
- https://github.com/mozilla/sumo/issues/1812
- https://github.com/mozilla/sumo/issues/1815
- https://github.com/mozilla/sumo/issues/1814
- https://github.com/mozilla/sumo/issues/1816

While the above are not considered release blockers, those are great candidates for future iterations of this work.

I'm moving this ticket inside the `release` column.
