### ISSUE TITLE
Wrong and missing products inside the Filter by product dropdown menu filter

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1843]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/topics/troubleshooting
2. Click on the `Filter by product` dropdown menu and note the listed products.
3. Access admin and filter the topics based on the `troubleshooting` topic slug: https://support.allizom.org/admin/products/topic/?slug=troubleshooting and note the listed products.

**Expected behavior**
The products listed inside the `Filter by product` dropdown menu should match the products listed inside the admin

**Actual behavior**
The products listed inside the `Filter by product` dropdown menu are either not found inside the admin list (example: `Firefox for Android` in this case) or some items which are displayed inside the admin list are not displayed inside the dropdown menu (example: `Firefox Reality` or `Firefox Private Network`

**Screenshots**
SUMO `Filter by product` dropdown menu for `troubleshooting` topic
![image](https://github.com/mozilla/sumo/assets/28087895/5db54130-8943-43fd-9df3-6a253fbb82af)

Products with `Troubleshooting` topic per admin:
![image](https://github.com/mozilla/sumo/assets/28087895/cb12d6b6-f5a7-4173-8c3d-233f1cccb707)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
This is working correctly: For topics listed in [the browse-by-topic list](https://github.com/mozilla/kitsune/blob/main/kitsune/sumo/__init__.py) we are adding all the products that have one of the keywords in the list. In the example that you mentioned, we are including the slugs `troubleshooting` and `fix-problems` for Troubleshooting. That's the reason why `Firefox for Android` is in there. 

`Firefox Reality` and `Firefox Private Network` are excluded because their visible flag is set to False. 

Based on the above I am closing the issue. Feel free to re-open if I missed anything here
