### ISSUE TITLE
Subtopics with redirects are returning 404

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#1873]
More info https://bugzilla.mozilla.org/show_bug.cgi?id=1907029

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6116

**Comment by emilghittasv** [comment]
I can confirm that this is verified fixed in `stage`. 

Links which contain a topic + subtopic are redirecting successfully.

Moving this ticket inside the `release` column.

**Comment by AliceWyman** [comment]
Reopen? https://support.mozilla.org/products/firefox/privacy-and-security/passwords-forms-search-and-history is a Page Not Found. This came up in the [Private Browsing - Use Firefox without saving history](https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history) article discussion [here](https://support.mozilla.org/en-US/kb/private-browsing-use-firefox-without-history/discuss/8134#post-27543), since that article links to that subtopic in the last section.
