### ISSUE TITLE
Check pageview counts in KB dashboard

### ISSUE THREAD

**Issue by escattone** [mozilla/sumo#1896]
One of our most experienced and active contributors has noted that the article titles and pageview counts in the [KB dashboard](https://support.mozilla.org/en-US/contributors) don't look correct:

> Looking at the dashboards, the titles of the popular articles are completely different and the number of page views are greatly reduced.

**Comment by AliceWyman** [comment]
This issue is still a problem.  I posted a comment in the SUMO room on Matrix and in the SUMO KB articles forum, [here](https://support.mozilla.org/en-US/forums/knowledge-base-articles/717125). 

The [KB dashboard](https://support.mozilla.org/en-US/contributors) and complete KB Overview, https://support.mozilla.org/en-US/contributors/kb-overview no longer show the most viewed articles in the last 30 days. Neither does the https://support.mozilla.org/en-US/contributors/most-visited list. Only articles with around 300 visits or less are shown. You have to look at the "Last 7 days" option to see articles with more visits.

**Comment by AliceWyman** [comment]
I noticed that the number of visits shown for popular articles is greatly reduced.  For example, in the https://support.mozilla.org/en-US/contributors/most-visited list, the article [Profiles - Where Firefox stores your bookmarks, passwords and other user data](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data) is near the bottom and shows the number of visits as 1. In fact, most of the listed articles show the number of visits as "1".

**Comment by AliceWyman** [comment]
Posted today by Kiki: https://support.mozilla.org/en-US/forums/contributors/717126 Temporary KB dashboard
(quote) _We recognized that the KB dashboard in Kitsune is broken recently after the migration from GA to GA4. While the team is figuring out [this issue](https://github.com/mozilla/sumo/issues/1896), we've created [this temporary dashboard](https://lookerstudio.google.com/reporting/40277d09-b83c-40e8-9b12-4c78130c3b31) for you to check on KB statistics. Thanks to Ryan Johnson for letting me fork his original dashboard so we can make this available for you all._<snip>

**Comment by emilghittasv** [comment]
Bug fix candidate for current sprint.

**Comment by escattone** [comment]
### Investigation Note
We're successfully gathering the pageviews from Google Analytics for all periods (7 days, 30 days, 90 days, 365 days), so there's something going wrong in another part of the data gathering for that view.

**Comment by escattone** [comment]
I found the source of the problem and submitted https://github.com/mozilla/kitsune/pull/6283. We should have a fix coming soon.

**Comment by emilghittasv** [comment]
The pageviews numbers inside the https://support.allizom.org/en-US/contributors are similar with the ones provided by the `stage` instance of LookerStudio.

I'm moving this ticket inside the `release` column.
