### ISSUE TITLE
Both the kb/new and /edit/metadata pages contain duplicated and old taxonomy topics

### ISSUE THREAD

**Issue by emilghittasv** [mozilla/sumo#1967]
**Steps to reproduce**
1. Go to https://support.allizom.org/en-US/kb/new or https://support.allizom.org/en-US/kb/tab-preferences-and-settings/edit/metadata
2. Observe the topics section.

**Expected behavior**
* No duplicated items.
* No topics from the old taxonomy.

**Actual behavior**
* Some topics are duplicated and belong to the old taxonomy.

**Screenshots**
![image](https://github.com/user-attachments/assets/4aad2bd4-1dda-4cc3-8d24-963717573517)

**Desktop:**
 - OS: Windows 11
 - Browser: Firefox

**Additional context**
This issue is reproducible in `stage` only.

**Comment by akatsoulas** [comment]
I would describe this more of "This is a feature, not a bug". This functionality queries and displays all the active topics that are associated with products. As we are cleaning up the KB by moving articles to the topics of the new taxonomy and archiving old topics, the duplicate topics will go away. In reality those topics are different objects with different slugs that have the same name and not duplicates.

I consider this more of a feature because it will allow us to deselect the old topics from the article and associate it to the new through the same UI
