### ISSUE TITLE
Move moderation tool to a separate url

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#2052]
The moderation tool should be moved to a separate URL and only specific groups should be able to access it.

**Comment by akatsoulas** [comment]
PR https://github.com/mozilla/kitsune/pull/6354

**Comment by akatsoulas** [comment]
Currently the URL is at `/moderate`

**Comment by emilghittasv** [comment]
I can confirm that:
- New questions submitted against freemium products end up inside the /moderate page list if the flagit-spam-autoflag and content_moderation waffle flags are enabled.
- New questions submitted against premium products don't end up inside the /moderate page.
- The "There is no content pending moderation." message is displayed if there are no flagged questions.
- The "View all deactivated users" button is visible and redirects the user to the /users/deactivation_log on click.
- The /moderate page is accessible only for users which have the flagit | flagged object| Can moderate flagged objects permission.
- Selecting a different topic from the "Change Topic" section will successfully change the topic associated with the question.
- The "View", "Edit" and "Delete" buttons are functional and no regressions encountered.
- The "Update Status" and "Update" buttons are functional an no regressions encountered.
- The question which was manually reported as misplaced will end up inside the /flagged list instead of /moderate.

During the verification of this ticket I've noticed that the question is removed from the /moderate page if manually flagged but not added back if the report was marked as invalid inside the /flagged page. (filled under https://github.com/mozilla/sumo/issues/2060)

Moving this ticket inside the `release` column.
