### ISSUE TITLE
[Mobile] There is some space on the recent revisions page on some contributors info

### ISSUE THREAD

**Issue by ovidiuboca1** [mozilla/sumo#294]
Prerequisites:
Use a mobile device. 

STR:

1. Go to https://support.allizom.org/en-US/kb/revisions?page=1
2. Look over the contributors info

ER: There is no space in these sections. 
AR: There is space in some contributors info. See the print screen. 
![Space issue](https://user-images.githubusercontent.com/54845678/77516010-43c4db80-6e82-11ea-8f2e-636951c56f33.jpeg)
NOTE: I don't think this is a big issue, so it can be moved to the next version.

**Comment by emilghittasv** [comment]
I am no longer able to reproduce this issue. It seems that the empty space which was previously visible is now filled with the "magnifying glass" icon.

Tested using Firefox on Huawei P40Pro.

Please feel free to re-open in case this issue is still reproducible.

![Screenshot_20230302_151939_org mozilla firefox](https://user-images.githubusercontent.com/28087895/222441778-ffdcf56f-7fd5-4a88-9dc7-cce8cd5ec16e.jpg)
