### ISSUE TITLE
 Unable to edit any description in media gallery

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/sumo#358]
Bugzilla entry
https://bugzilla.mozilla.org/show_bug.cgi?id=1563194

**Comment by mirunacurtean** [comment]
Unable to reproduce with simple contributor account that can edit their own uploads or  with multiple permissions account that can edit any post. 
![image](https://user-images.githubusercontent.com/53306802/171582729-9c0d9a45-956a-4b14-af16-ce08488a4db6.png)
![image](https://user-images.githubusercontent.com/53306802/171583320-cf0dba57-0f0b-4cce-a17f-fd7ca7a8a359.png)

**Comment by akatsoulas** [comment]
@mirunacurtean shall we close it then?

**Comment by upwinxp** [comment]
I can still reproduce the bug. Have you tried saving the edited description? I'm able to open the "Edit image" page and enter a new description, but clicking the "Save image" button gives me _Oh, no! It looks like an unexpected error occurred_.

**Comment by mirunacurtean** [comment]
@akatsoulas Sorry, @upwinxp is right, these sort of images do result in the specified error when I try saving the edit.  It does not happen to new images I've tried with, like in the first screenshot. 
https://support.allizom.org/en-US/gallery/image/29541
![edit fx57](https://user-images.githubusercontent.com/53306802/171648782-11fc54e0-1de7-4730-a0c7-1fa3e8a3cbbf.gif)

**Comment by mirunacurtean** [comment]
Verified fixed using the Fx examples but also a new upload on desktop and mobile to ensure regressions have not appeared in this area. 
The images can be edited muliple times using text and symbols and these edits can be sucessfully saved. 
![image](https://user-images.githubusercontent.com/53306802/176170717-86f310f8-8641-44dc-ade1-fed29164e4fd.png)

I did encounter an issue with the images that would not display, but I'm bot sure it's a regression or just that it only occurs on stage due to data issues. I've added https://github.com/mozilla/sumo/issues/1061 for it.
