### ISSUE TITLE
Cannot filter Recent Revisions based on users on desktop (stage) and mobile (stage and production)

### ISSUE THREAD

**Issue by mirunacurtean** [mozilla/sumo#535]
**Affected platforms:**
Windows 10 64-bit
Android 9.0

**Browser version:**
FF Release 78.0.1
Firefox 68.10.0
Chrome 83.0.4

**Environment:**
**Stage  - Desktop**
**Stage and Production - Mobile**

**Precondition:** 
Login with account in order to have access to Contributor Tools. 

**Steps to reproduce:**

1.Go to https://support.allizom.org/en-US/kb/revisions?locale=&users=&start=&end=
2. Pick an editor username from the tabel and input it in the Users field. 
3. On desktop hit enter.  On mobile select Next (that should be an alternative to Enter)

**Expected results:**
On desktop, In Production, filtering is performed based on User. 
https://support.mozilla.org/en-US/kb/revisions?locale=&users=Artist&start=&end=

**Actual Results:**
Page seems to be refreshing but results are not filtered based on username.

![Recent Revisions sorting by users is not performed ](https://user-images.githubusercontent.com/53306802/86933123-e3149280-c142-11ea-9ccd-b68f18128683.gif)

**Comment by mirunacurtean** [comment]
Should have checked before adding [this](https://github.com/mozilla/sumo/issues/1092). At lest I can confirm it still occurs.

**Comment by emilghittasv** [comment]
@akatsoulas 

From my investigations I've noticed that the recent revisions page can **actually** filter content based on username but **not** based on the display name.

The problem here is that it's not obvious for a user which is the username and which is the display name of the editor (since if the editor has a display name set the display name is going to take priority/is going to get displayed inside the recent revisions editor field instead of username)

I'm attaching a screencast showing this:
![recentRevisionsFilter](https://github.com/user-attachments/assets/1d9b1a0a-7f1d-4246-9dd8-f72f9451e930)


We should probably extend the query to also search for the display name? 

Would you prefer closing this ticket and starting fresh with a new one?

**Comment by akatsoulas** [comment]
Yes please, let's track this elsewhere
