### ISSUE TITLE
Enable deep links in KB articles

### ISSUE THREAD

**Issue by jonichan** [mozilla/sumo#807]
We'd like to enable deep links, which don't use the regular HTTP(s) or mailto protocol. Kitsune isn't allowing us to use the <a> tags or [ ] wiki markup because deep links don't use the https(s) or mailto protocols.

STR:
1. Create a new article.
2. Enter firefox://deep-link?url=/default-browser/system-settings in the body as is or using <a> or [ ] 

Expectation: firefox://deep-link?url=/default-browser/system-settings should be linkified.
Actual result: firefox://deep-link?url=/default-browser/system-settings is showing up as plain text and we can't click on it.

**Comment by LeoMcA** [comment]
Some rough notes from investigating this yesterday:

It looks like our wiki parser strips out `<a>` tags, and detects links using a regex with an explicit list of protocols within. These behaviours are controlled with a bunch of variables in the root of `wikimarkup.paser` (like `_htmlelements` and `_bracketedLinkPat`) which it's probably *a bad idea™* to attempt to monkey patch (indeed, I don't know enough about python monkey patching to know if it's even possible).

I think the best approach is probably to do a `registerInternalLinkHook` and then the syntax can be something like `[[Deep Link:firefox://deep-link?url=/default-browser/system-settings]]`

@jonichan is this iOS specific formatting? Does Android have similar functionality, what do those deep links look like? I'm asking because we could possibly reduce the syntax to just something like `[[Deep Link:/default-browser/system-settings]]` and generate the rest of the url in the backend - but deep links would need consistent formatting across platforms then.
